sonar.projectKey=vz-book-2026
sonar.projectName=vz-book-2026

sonar.sources=src
sonar.exclusions=**/*.test.js,**/*.test.ts,dist/**,.astro/**,node_modules/**

sonar.tests=test
sonar.test.inclusions=test/**/*.test.js,test/**/*.test.ts,test/e2e/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
